### ISSUE TITLE
support python 2.4

### ISSUE THREAD

**Issue by fulv** [gforcada/ansible-compile-python#1]
I would like to use it to install python 2.4.  I'll try to add support for it, and create a PR if I succeed.

**Comment by fulv** [comment]
python 2.4 can be added very easily.  The problem is virtualenv.  According to my research, 1.7.2 was the last version of virtualenv that supported python 2.4.  This is doable, with just a few more special cases in the `tasks/venv.yml` and the `defaults/main.yml` files.  However, even after building python 2.4 and a supposedly compatible virtualenv, it still does not run due to a missing `zlib`:

```
root@wda:~# /srv/python2.4.6/bin/virtualenv
Traceback (most recent call last):
  File "/srv/python2.4.6/bin/virtualenv", line 2, in ?
    import virtualenv
  File "/srv/python2.4.6/lib/python2.4/site-packages/virtualenv.py", line 19, in ?
    import zlib
ImportError: No module named zlib
```

However, I get the same exact error even if I try to run virtualenv out of python2.6.9, so maybe this should be a different issue.

**Comment by fulv** [comment]
For the record, I was able to fix this by following the first answer in http://stackoverflow.com/questions/12344970/building-python-from-source-with-zlib-support:

```
Edit /Modules/Setup and uncomment the line:

zlib zlibmodule.c -I$(prefix)/include -L$(exec_prefix)/lib -lz
```

Then re-ran `./configure`, `make` and `make install`.  Now python2.4 can import `zlib`, so virtualenv works.

However, automating this change as part of the playbook is trickier.

**Comment by gforcada** [comment]
@fulv on that stackoverflow answer they say that installing `dpkg-dev` should fix it as well. I will give it a try.

**Comment by gforcada** [comment]
mmmh doesn't really work and it was already part of the requirements...

**Comment by fulv** [comment]
@gforcada neat!  Yes, it works for 2.4 now.  However, for 2.6 there is still an error (see #2).

**Comment by gforcada** [comment]
Merged manually in https://github.com/gforcada/ansible-compile-python/commit/71be6a485f940f60f68bfcf0caf1f465a9c57e89

Thanks!
